services:
  db:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - "6379:6379"

  # rtsptoweb:
  stream-server:
    restart: unless-stopped
    image: ghcr.io/deepch/rtsptoweb:latest
    volumes:
      - ./RtspConfig.json:/config/config.json
    ports:
      - "8080:8080"


  # teleicu-middleware
  teleicu-middleware:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8090"]
    volumes:
      - .:/app
    depends_on:
      - redis
      - stream-server
      - db
    env_file:
      - ./.env
    ports:
      - "8090:8090"

  celery:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    command: ["sh", "-c", "/app/scripts/start-celery.sh"]
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - teleicu-middleware

  # proxies requests to internal services
  reverse-proxy:
    restart: unless-stopped
    build:
      context: nginx
      dockerfile: ../docker/nginx.Dockerfile
    depends_on:
      - teleicu-middleware
    ports:
      - "8001:8001"

volumes:
  postgres-data:
