services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    restart: always

  # rtsptoweb:
  stream-server:
    restart: always
    image: ghcr.io/deepch/rtsptoweb:latest
    volumes:
      - ./RtspConfig.json:/config/config.json
    ports:
      - "8080:8080"


  # teleicu-middleware
  teleicu-middleware:
    restart: always
    image: ghcr.io/10bedicu/teleicu_gateway:lab-analyzer
    command: ["sh", "-c", "/app/start-backend.sh"]
    depends_on:
      - redis
      - stream-server
      - db
    env_file:
      - ./.env
    ports:
      - "8090:8090"

  hl7-server:
    restart: unless-stopped
    image: ghcr.io/10bedicu/teleicu_gateway:lab-analyzer
    command: ["sh", "-c", "/app/start-hl7-server.sh"]
    env_file:
      - ./.env
    depends_on:
      - teleicu-middleware
    ports:
      - "2577:2577"

  dummy-lab-analyzer:
    restart: unless-stopped
    image:  ghcr.io/10bedicu/mock_lab_analyzer:latest
    environment:
      - MLLP_SERVER_ADDRESS=hl7-server:2577
      - LISTEN_PORT=2575

  celery:
    restart: always
    image: ghcr.io/10bedicu/teleicu_gateway:lab-analyzer
    command: ["sh", "-c", "/app/start-celery.sh"]
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - teleicu-middleware

  # proxies requests to internal services
  reverse-proxy:
    restart: always
    image: ghcr.io/10bedicu/teleicu_gateway_nginx:latest
    depends_on:
      - teleicu-middleware
    ports:
      - "8001:8001"

volumes:
  postgres-data:
