x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

services:
  db:
    image: postgres:17
    restart: always
    logging: *default-logging
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    restart: always
    logging: *default-logging

  # rtsptoweb:
  stream-server:
    restart: always
    image: ghcr.io/deepch/rtsptoweb:latest
    logging: *default-logging
    volumes:
      - ./RtspConfig.json:/config/config.json
    ports:
      - "8080:8080"


  # teleicu-middleware
  teleicu-middleware:
    restart: always
    image: ghcr.io/10bedicu/teleicu_gateway:latest
    logging: *default-logging
    command: ["sh", "-c", "/app/start-backend.sh"]
    depends_on:
      - redis
      - stream-server
      - db
    env_file:
      - ./.env
    ports:
      - "8090:8090"

  celery:
    restart: always
    image: ghcr.io/10bedicu/teleicu_gateway:latest
    logging: *default-logging
    command: ["sh", "-c", "/app/start-celery.sh"]
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - teleicu-middleware

  # proxies requests to internal services
  reverse-proxy:
    restart: always
    image: ghcr.io/10bedicu/teleicu_gateway_nginx:latest
    logging: *default-logging
    depends_on:
      - teleicu-middleware
    ports:
      - "8001:8001"

volumes:
  postgres-data:
