limit_req_zone $binary_remote_addr zone=ip:10m rate=20r/s;

server {
    listen 8001;

    location /test {
        limit_req zone=ip burst=12 delay=8;
        root /var/www/;
    }

    location /update_observations {
        return 404;
    }

    location /start {
        limit_req zone=ip burst=12 delay=8;
        proxy_pass http://roverr_rtsp_stream:8080;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    location /stream {
        limit_req zone=ip burst=12 delay=8;
        proxy_pass http://roverr_rtsp_stream:8080;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache off;

        add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        expires off;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    location /list {
        limit_req zone=ip burst=12 delay=8;
        proxy_pass http://roverr_rtsp_stream:8080;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /stop {
        limit_req zone=ip burst=12 delay=8;
        proxy_pass http://roverr_rtsp_stream:8080;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /logger {
        proxy_pass http://teleicu_middleware:8090;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    location / {
        limit_req zone=ip burst=12 delay=8;
        proxy_pass http://teleicu_middleware:8090;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache off;

        add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        expires off;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}