# Generated by Django 5.0.6 on 2024-06-01 21:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('OnvifAsset', 'ONVIF'), ('HL7MonitorAsset', 'HL7MONITOR'), ('VentilatorAsset', 'VENTILATOR')], default='HL7MonitorAsset', max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('access_key', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, default=80, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['external_id', 'ip_address'], name='middleware__externa_5ec6b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_external_id', models.UUIDField()),
                ('status', models.CharField(max_length=255)),
                ('data', models.TextField()),
                ('response', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rounds', to='middleware.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['asset_external_id'], name='middleware__asset_e_f8b097_idx')],
            },
        ),
    ]
