# Generated by Django 5.0.6 on 2024-06-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0002_remove_asset_middleware__externa_5ec6b8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('ONVIF', 'OnvifAsset'), ('HL7MONITOR', 'HL7MonitorAsset'), ('VENTILATOR', 'VentilatorAsset')], default='HL7MonitorAsset', max_length=20),
        ),
    ]
